// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnXFuo3EJwapAgDaw5ZFt1q0mUsJieq7A',
    appId: '1:368112514569:web:388d808bfc7f73bbf1ead8',
    messagingSenderId: '368112514569',
    projectId: 'chamada-inteligente',
    authDomain: 'chamada-inteligente.firebaseapp.com',
    storageBucket: 'chamada-inteligente.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZCoWNmv0uQhjLZt-TeCBvMM5kuflgMh4',
    appId: '1:368112514569:android:8f65d0c349a148a7f1ead8',
    messagingSenderId: '368112514569',
    projectId: 'chamada-inteligente',
    storageBucket: 'chamada-inteligente.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt3RSzQtXRffqfFSuiL1bJlFlI3HAeVRg',
    appId: '1:368112514569:ios:7e36d448ed392e1ff1ead8',
    messagingSenderId: '368112514569',
    projectId: 'chamada-inteligente',
    storageBucket: 'chamada-inteligente.appspot.com',
    iosBundleId: 'com.example.chamadainteligente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt3RSzQtXRffqfFSuiL1bJlFlI3HAeVRg',
    appId: '1:368112514569:ios:da277872ae8f2bbaf1ead8',
    messagingSenderId: '368112514569',
    projectId: 'chamada-inteligente',
    storageBucket: 'chamada-inteligente.appspot.com',
    iosBundleId: 'com.example.chamadainteligente.RunnerTests',
  );
}
